name: Other
description: For everything else
assignees: ['CommunityMaintained']
body:
  - type: markdown
    attributes:
      value: '**PLEASE NOTE:**'
  - type: markdown
    attributes:
      value: |
        Only critical issues will be addressed in this fork. For new features or minor issues, please consider switching to [Tubeless](https://github.com/CommunityMaintained/tubeless). See [Pinchflat vs. Tubeless](https://github.com/CommunityMaintained/pinchflat/blob/master/priv/static/images/pinchflat-vs-tubeless.png) for more details.
  - type: textarea
    id: text
    attributes:
      label: Text field
    validations:
      required: true
  - type: upload
    id: screenshots
    attributes:
      label: Screenshots
      description: 'If applicable, add screenshots for additional context.'
    validations:
      required: false
  - type: checkboxes
    id: agreements
    attributes:
      label: 'I have verified the following:'
      description: I confirm this is a critical issue that needs to be addressed in this fork.
      options:
        - label: This is a critical issue that needs to be addressed in this fork.
          required: true
