name: Dev Image Cleanup

on:
  schedule:
    - cron: '5 0 * * *' # every day at 00:05 UTC

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old dev images
    steps:
      - uses: snok/container-retention-policy@d3bdcf5ce9b05f685154e4a16c39233b245e3d53 # v3.1.0
        with:
          account: communitymaintained
          token: ${{ secrets.IMG_RETENTION }}
          image-names: pinchflat-dev
          image-tags: 'rc-* pr-*' # target any image that has a tag starting with the word test or dev
          cut-off: 7d
          dry-run: false
